version: "3.8"

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "./:/home/promitia/code"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
